apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: infinispan-statefulset
  namespace: openshift-gitops
spec:
  destination:
    namespace: infinispan1
    server: https://kubernetes.default.svc
  project: default
  source:
    path: k8s/statefulset
    repoURL: https://github.com/blues-man/infinispan-gitops
    targetRevision: main
  syncPolicy:
    automated:
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
